{
	"version": 1548529436,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/aliado-sheet0.png",
		"images/aliado-sheet1.png",
		"images/enemigo-sheet0.png",
		"images/enemigo-sheet1.png",
		"images/jugador-sheet0.png",
		"images/jugador-sheet1.png",
		"images/utileria-sheet0.png",
		"images/utileria-sheet1.png",
		"images/utileria-sheet2.png",
		"images/utileria-sheet3.png",
		"images/stickbase-sheet0.png",
		"images/stick-sheet0.png",
		"images/pvapor.png",
		"images/pconfetia.png",
		"images/pconfetir.png",
		"images/pconfetiv.png",
		"images/pgloboa.png",
		"images/pglobor.png",
		"images/pglobov.png",
		"images/fondo.png",
		"images/objeto.png",
		"images/canvas.png",
		"images/agua-sheet0.png",
		"images/zreloj-sheet0.png",
		"images/zgui-sheet0.png",
		"images/zgui-sheet1.png",
		"images/zrapido-sheet0.png",
		"a3-tono ascendiendo 1 revertido.m4a",
		"a3-tono ascendiendo 1 revertido.ogg",
		"a3-tono ascendiendo 1.m4a",
		"a3-tono ascendiendo 1.ogg",
		"a3-desplazamiento 1 revertido.m4a",
		"a3-desplazamiento 1 revertido.ogg",
		"a3-desplazamiento 1.m4a",
		"a3-desplazamiento 1.ogg",
		"a3-tapon 4.m4a",
		"a3-tapon 4.ogg",
		"a3-tono ascendiendo 6.m4a",
		"a3-tono ascendiendo 6.ogg",
		"a1-niños alegres.m4a",
		"a1-niños alegres.ogg",
		"a3-reloj.m4a",
		"a3-reloj.ogg",
		"a3-timbre.m4a",
		"a3-timbre.ogg",
		"c3-musica de circo 8.m4a",
		"c3-musica de circo 8.ogg",
		"c3-musica de accion 1.m4a",
		"c3-musica de accion 1.ogg",
		"c3-musica de carrera 1.m4a",
		"c3-musica de carrera 1.ogg",
		"c3-musica de selva 1.m4a",
		"c3-musica de selva 1.ogg",
		"c3-musica de circo 3.m4a",
		"c3-musica de circo 3.ogg",
		"c3-musica de invierno 2.m4a",
		"c3-musica de invierno 2.ogg",
		"c3-musica de villano 1.m4a",
		"c3-musica de villano 1.ogg",
		"c3-musica de miedo 3.m4a",
		"c3-musica de miedo 3.ogg",
		"c3-musica de accion 3.m4a",
		"c3-musica de accion 3.ogg",
		"c3-musica de carrera 3.m4a",
		"c3-musica de carrera 3.ogg",
		"c3-musica de accion 4.m4a",
		"c3-musica de accion 4.ogg",
		"c3-musica de circo 4.m4a",
		"c3-musica de circo 4.ogg",
		"c3-musica de selva 2.m4a",
		"c3-musica de selva 2.ogg",
		"c3-musica de circo 5.m4a",
		"c3-musica de circo 5.ogg",
		"c3-musica de miedo 2.m4a",
		"c3-musica de miedo 2.ogg",
		"c3-musica de invierno 1.m4a",
		"c3-musica de invierno 1.ogg",
		"c3-musica de circo 6.m4a",
		"c3-musica de circo 6.ogg",
		"c3-musica de circo 2.m4a",
		"c3-musica de circo 2.ogg",
		"c3-musica de miedo 1.m4a",
		"c3-musica de miedo 1.ogg",
		"c3-musica de circo 7.m4a",
		"c3-musica de circo 7.ogg",
		"c3-musica de carrera 4.m4a",
		"c3-musica de carrera 4.ogg",
		"c3-musica de carrera 2.m4a",
		"c3-musica de carrera 2.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"j16a.csv",
		"j4a.png",
		"j9a.csv",
		"juegos.csv",
		"audio.html",
		"ayuda micro.gif",
		"ayuda mousea.gif",
		"ayuda mousec.gif",
		"ayuda teclado.gif",
		"creditos.html",
		"j-1.html",
		"j-1a.png",
		"j-1b.png",
		"j-1c.png",
		"j-1d.png",
		"j-1e.png",
		"j-1f.png",
		"j-1g.png",
		"j-1h.png",
		"j-1i.png",
		"j-1j.png",
		"j-1k.png",
		"j-1l.png",
		"j-1m.png",
		"j-1n.png",
		"j-1ñ.png",
		"rankingentrada.html",
		"rankingtabla.html",
		"gui test.csv",
		"preguntas.csv",
		"test.html",
		"cortina horizontal.png",
		"cortina vertical.png",
		"cuerda.png",
		"madera.png",
		"estilos.css",
		"eventos.js",
		"gui barra.csv",
		"gui menu.csv",
		"gui pausa.csv",
		"gui salto.csv",
		"tareas.csv",
		"muro de ladrillos.png",
		"cerca.png",
		"j2.html",
		"j2a.gif",
		"j2b.gif",
		"j3.html",
		"j4.html",
		"j8.html",
		"j9.html",
		"j15.html",
		"j18.html",
		"j9a.png",
		"j9b.png",
		"j15a.gif",
		"j15b.gif",
		"j18a.png",
		"j18b.png",
		"j10a.gif",
		"j7.html",
		"j7a.png",
		"j7b.png",
		"j11.html",
		"j11a.png",
		"j11b.png",
		"j12.html",
		"j12a.gif",
		"j12b.png",
		"j13.html",
		"j13a.png",
		"j13b.png",
		"j17.html",
		"j17a.gif",
		"j17b.png",
		"j10.html",
		"j10b.png",
		"j1.html",
		"j5.html",
		"j6.html",
		"j14.html",
		"j16.html",
		"j19.html",
		"j20.html",
		"j6a.gif",
		"j20b.png",
		"j20a.gif",
		"j19b.png",
		"j19a.png",
		"j16a.png",
		"j14b.png",
		"j14a.png",
		"j5b.png",
		"j6b.png",
		"j5a.png",
		"firebase.js",
		"mazegen.js",
		"adapter.js",
		"penumbra.png",
		"zlib_and_gzip.min.js"
	]
}